#!/bin/bash
set -e

echo ">> Getting elixir dependencies"

# Ensure we're in the app root directory.
cd "$(dirname "$0")"/..

export MIX_ENV="test"
export LC_ALL=en_US.UTF-8

source web/elm/paths.env
mix do deps.get, compile

echo
echo ">> Getting Brunch dependencies"
npm install

cd web/elm
echo
echo ">> Getting Elm dependencies"
elm package install -y
cd ../..

echo
echo ">> Building assets using brunch"

# Workaround some odd babel bug that only occurs on CI

[ "$CIRCLECI" ] && ln -sf $PWD/node_modules/babel-brunch/node_modules/babel-preset-es2016 node_modules/

node_modules/brunch/bin/brunch build
