#!/bin/bash
set -e

export ENABLE_DB_LOGGING=true

echo ">> Making backup and downloading database from $1"
heroku pg:backups capture -a $1
curl --output /tmp/data.dump `heroku pg:backups public-url -a $1`

echo
echo ">> Preparing to import"
mix ecto.drop
mix ecto.create

echo
echo ">> Importing database from $1 as review_dev"
if [ $DEVBOX ]; then
  PGUSER=postgres PGPASSWORD=dev pg_restore --no-acl --no-owner -h localhost -d review_dev -p $(service_port postgres) /tmp/data.dump
else
  pg_restore --no-acl --no-owner -h localhost -d review_dev /tmp/data.dump
fi

echo ">> Done"
