#!/bin/bash
set -e

# Ensure we're in the app root directory. Required when running
# directly within a docker container without any wrapping script.
cd "$(dirname "$0")"/..

export MIX_ENV="test"
export LC_ALL=en_US.UTF-8

source web/elm/paths.env
mix do deps.get, deps.compile, compile
npm install

cd web/elm
elm package install -y

# The elm-brunch plugin does not compile elm when brunch-build is run, only
# when changes are detected. This makes it work on the first run too.
rm -f ../static/vendor/compiled_elm/*
elm make modules/CommitList.elm modules/CommitList/View.elm modules/CommitList/Action.elm modules/CommitList/Model.elm --output ../static/vendor/compiled_elm/elm-app.js

cd ../..

node_modules/brunch/bin/brunch build
