#!/bin/bash
set -e

# Ensure we're in the app root directory.
cd "$(dirname "$0")"/..

export MIX_ENV="test"
export LC_ALL=en_US.UTF-8

source web/elm/paths.env
mix do deps.get, compile
npm install

cd web/elm
elm package install -y
cd ../..

node_modules/brunch/bin/brunch build
